version: "3"

services:

  postgis:
    image: starefossen/pgrouting:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ~/Documents/docker/postgis:/var/lib/postgresql/data

