version: "3"

services:

  postgis:
    image: mdillon/postgis:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ~/Documents/docker/postgis:/var/lib/postgresql/data

  maptiles:
    image: klokantech/openmaptiles-service:latest
    restart: always
    ports:
      - 1111:80
    volumes:
      - ~/Documents/docker/maptiles:/data

